# Generated by Django 4.2.4 on 2023-08-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='category/images/%m')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/images/%m')),
                ('price', models.DecimalField(decimal_places=0, max_digits=30)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('review', models.CharField(default=30, max_length=50)),
                ('slug', models.SlugField(max_length=30)),
                ('color', models.CharField(choices=[('white', 'white'), ('black', 'black')], max_length=10)),
                ('size', models.CharField(choices=[('M', 'M'), ('X', 'X'), ('L', 'L'), ('XL', 'XL')], max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apps.category')),
            ],
        ),
    ]
